# Instal tensorflow
You can install it using command prompt or directly here

In [ ]:
!pip install tensorflow

In [10]:
import tensorflow as tf
from tensorflow import GradientTape

# Constant
Before calculating gradients we must know about constants and variables. We can not use a basic constant or a basic python variable here, tensorflow uses computation graphs for calculating gradients that's why we use tf.constant and tf.Variable here. tf.constant is a tensor whose value can not be changed, and tf.Variable is also a tensor whose value can be changed unlike tf.constant

In [47]:
c = tf.constant(4.0)
c

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

# Variable
These are also called trainable variables, as we will see when we move on to the main tensorflow section how they are used in training neural nets. Their values can be changes over time. 


In [53]:
v = tf.Variable(23.0)
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=23.0>

# Gradient Tape
Using gradient tape we can compute gradients. The GradientTape context will automatically track tf.Variable tensors but it will not track tf.Constant tensors. Let's take a function as an example, compute its gradients ourselves and then use GradientTape

# $f(x,y) = 2x^2 +3y + 5x^2y$

### The gradients for this function

# $\frac{\partial f(x,y)}{\partial x} =f'_x = 4x + 10xy $ 
# $\frac{\partial f(x,y)}{\partial y} =f'_y = 3 + 5x^2 $ 

### At x = 4, y = 8

# $\frac{\partial f(x,y)}{\partial x} = 4\cdot4 + 10\cdot4\cdot8 = 16+320 =326 $
# $\frac{\partial f(x,y)}{\partial x} = 3 + 5\cdot4^2 = 3+80 =83 $

# Define Function with tf.function wrapper

In [55]:
@tf.function
def f(x,y):
    return 2*x**2 +3*y+ 5*(x**2)*y

## Define Tf.Variable(s) with values 4 and 8

In [56]:
x = tf.Variable(4.0)
y = tf.Variable(8.0)


## Using GradientTape

In [57]:
with GradientTape() as tape:
#     the tape tracks operations in this context... 
    z = f(x,y)

gradients = tape.gradient(z,[x,y])
# this tape can only be used once 
print(gradients)
    

[<tf.Tensor: shape=(), dtype=float32, numpy=336.0>, <tf.Tensor: shape=(), dtype=float32, numpy=83.0>]


# Using tf.constant instead
It's not advised that you use tf.constant but just to prove a point let's see what happens if we do use it

In [51]:
x = tf.constant(4.0)
y = tf.constant(8.0)
with GradientTape() as tape:
#     the tape tracks operations in this context... 
    z = f(x,y)

gradients = tape.gradient(z,[x,y])
# this tape can only be used once 
print(gradients)
    

[None, None]


You get none as the answer, we can use the tape.watch(t) to track the variable that we want to track(in this case where the tensor is not a tf.Variable and is not tracked by default)

In [52]:
x = tf.Variable(4.0)
y = tf.Variable(8.0)
with GradientTape() as tape:
#     the tape tracks operations in this context... 
    tape.watch(x)
    tape.watch(y)
    z = f(x,y)

gradients = tape.gradient(z,[x,y])
# this tape can only be used once 
print(gradients)
    

[<tf.Tensor: shape=(), dtype=float32, numpy=336.0>, <tf.Tensor: shape=(), dtype=float32, numpy=83.0>]
